### ISSUE TITLE
Add a Gradio interface

### ISSUE THREAD

**Issue by ElmorenohWTF** [camenduru/DeepFloyd-IF-colab#4]
I think this would make it much easier to use. I was looking at Deepfloyd's Github and it looks like it supports Gradio.

**Comment by camenduru** [comment]
Hi @ElmorenohWTF 👋 please check 

![image](https://user-images.githubusercontent.com/54370274/236042477-67ae7652-f67f-4964-86d1-2a958ad3f6f6.png)
